EMAIL_REQUIRED_SETTINGS = [
    "EMAIL_HOST",
    "EMAIL_PORT",
    "EMAIL_HOST_USER",
    "EMAIL_HOST_PASSWORD",
    "EMAIL_USE_TLS",
    "DEFAULT_FROM_EMAIL",
]

NOTIFIER_EXTRA_REQUIRED_SETTING = "ADMIN_EMAIL"
